spring.application.name=SplitSewa

## Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#spring.datasource.url=jdbc:mysql://localhost:3306/SplitSewa
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=thisismysecretkeythatisatleast32characterslong
jwt.expiration-ms=8640000



## JWT

#jwt.secret=${JWT_SECRET}
#jwt.expiration-ms=${JWT_EXPIRATION_MS}

# Port
server.port=8080